name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: []
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: Desctibe the bug
      description: "A clear and concise description of what the bug is."
      placeholder: "I was trying to..."
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      placeholder: |
        1.
        2.
        ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: "What effect do you expect after fix?"
      placeholder: "I expect to see..."
    validations:
      required: true
  - type: input
    id: dart_version
    attributes:
      label: Dart version
      description: What version of dart are you running?
      placeholder: ">=3.1.0 <4.0.0"
    validations:
      required: true
  - type: input
    id: flutter_version
    attributes:
      label: Flutter version
      description: What version of flutter are you running?
      placeholder: 2.6.7, 3.0.0, 3.1.0, etc.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Package version
      description: What version of our software are you running?
      options:
        - "1.0.0"
        - "1.0.1"
        - "1.0.2"
        - "1.0.3"
        - "1.0.4"
        - "1.1.0"
        - "1.2.0"
        - "1.2.1"
        - "1.3.0"
        - "1.4.0"
        - "1.4.1"
        - "1.4.2"
        - "1.4.3"
        - "1.4.4"
        - "1.5.0"
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: What platform are you seeing the problem on?
      multiple: true
      options:
        - iOS
        - Android
        - Web
        - Windows
        - macOS
        - Linux
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      placeholder: "Paste logs here or tell us about not having any logs."
      render: shell
    validations:
      required: true