name: hooked_bloc
description: Flutter package that simplifies injection and usage of Bloc/Cubit.
version: 1.4.4
repository: https://github.com/Iteo/hooked_bloc
issue_tracker: https://github.com/Iteo/hooked_bloc/issues
homepage: https://github.com/Iteo/hooked_bloc
documentation: https://github.com/Iteo/hooked_bloc/blob/main/README.md

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  flutter_hooks: ^0.20.1
  meta: ^1.10.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mocktail: ^1.0.2

flutter:
