name: hooked_bloc
description: Flutter package that simplifies injection and usage of Bloc/Cubit.
version: 1.7.0
repository: https://github.com/Iteo/hooked_bloc
issue_tracker: https://github.com/Iteo/hooked_bloc/issues
homepage: https://github.com/Iteo/hooked_bloc
documentation: https://github.com/Iteo/hooked_bloc/blob/main/README.md

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  flutter_hooks: ^0.21.0
  meta: ^1.15.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

flutter:
