name: hooked_bloc
description: Flutter package that simplifies injection and usage of Bloc/Cubit.
version: 1.1.0
repository: https://github.com/Iteo/hooked_bloc
issue_tracker: https://github.com/Iteo/hooked_bloc/issues
homepage: https://github.com/Iteo/hooked_bloc
documentation: https://github.com/Iteo/hooked_bloc/blob/develop/README.md

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  flutter_hooks: ^0.18.2+1
  meta: ^1.7.0
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  mocktail: ^0.3.0

flutter:
