name: Build

on:
  pull_request:
    branches: [ master, develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10.5'

      - name: Install dependencies
        run: flutter pub get
        
      - name: Generate files
        run: flutter pub run build_runner build
        working-directory: example
        
      - name: Analyze
        run: flutter analyze
        
      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage to codecov
        run: curl -s https://codecov.io/bash | bash

