name: Test

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.3'

      - name: Install dependencies
        run: flutter pub get
        
      - name: Generate files
        run: flutter pub run build_runner build
        working-directory: example
        
      - name: Analyze
        run: flutter analyze
        
      - name: Run tests
        run: flutter test --coverage
